Refactor data base
elagarrigue/AyDS23-NewYork3 pull request #2
Opened 2023-04-25 14:28 UTC by CoachVach

2023-04-25 14:52 UTC, AgusF22 requested changes

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +
Borrar linea de mas

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +
Borrar linea de mas

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +
Borrar linea de mas

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +
Borrar linea de mas

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +    }
Revisar esto. Un metodo vacio me parece un smell

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.java
No deberian haber tocado este archivo, hagan el rollback a como estaba

2023-04-25 14:52 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +        fun getInfo( artist: String): String? {
el espacio entre ( y artist, no se si se considera mal, pero al menos a mi me da TOC

2023-04-25 15:58 UTC, AgusF22 approved these changes

2023-04-26 06:10 UTC, DaniloLaColla approved these changes
Algunos saltos de linea innecesarios, en lo demas estoy de acuerdo

2023-04-27 00:35 UTC, AgusF22 reviewed
El otro dia estuve leyendo que en general es un smell tener lineas en blanco dentro de un metodo, porque si hay que dividirlo en partes significa que no hay una alta cohesion. Ademas de lo que nos marcaron en la anterior entrega, de que apretar mas enter no hace el codigo mas legible

2023-04-27 00:35 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +
esta linea yo la borraria

2023-04-27 00:54 UTC, merged