Refactor other info window
elagarrigue/AyDS23-NewYork3 pull request #3
Opened 2023-04-25 20:43 UTC by AgusF22

2023-04-25 21:49 UTC, nicolastradivarius requested changes

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        private const val NEW_YORK_TIMES_URL = "https://api.nytimes.com/svc/search/v2/"
Se pueden definir como constantes globales al inicio del archivo

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistInfo(artistName: String?) {
Revisar el código de la función en el Scrum del miércoles 26. Tiene pinta de estar haciendo más de una cosa a la vez, con diferentes niveles de abstracción

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            )
Pueden extraer la formación de este texto en una función aparte, para que `textToHtml()` consista sólo de "`builder.append`'s"

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            )
Analizar también si es posible evitar el uso de los `!!`.

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/res/layout/activity_other_info.xml
El cambio fue necesario debido a que se cambió el nombre de la variable a uno más significativo.

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    val abstract = response[DOCS].asJsonArray[0].asJsonObject[ABSTRACT]
¿Se puede renombrar `abstract` a algo que refleje más su significado? Si no, ignorar este comentario.

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    }
Se podría extraer en una o varias funciones aparte. Por ejemplo, una función que construya la `response` y demás cosas, y que evalúe guardar el artista en la base de datos.

2023-04-25 21:49 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    }
Y lo mismo para la parte del `Intent`, quizá.

2023-04-25 21:52 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +import java.util.*
El comentario es sólo para la línea `20. import java.util.*`

2023-04-25 22:39 UTC, CoachVach requested changes

2023-04-25 22:39 UTC, CoachVach commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistInfo(artistName: String?) {
Comparto, podría modularse y evitar capturar distintos niveles de abstracción. Por ejemplo, quedaría mas legible diviendose entre  getInfoFromDatabase y getInfoFromApi.

2023-04-25 22:39 UTC, CoachVach commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                "<b>" + term!!.uppercase(Locale.getDefault()) + "</b>"
En vez de utilizar Regex, vi que podría simplificarse utilizando replace con un patrón de remplazo. Sin embargo, es solo una alternativa para lograr lo mismo, asi que ignorar si no es de utilidad.

2023-04-25 22:48 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    val abstract = response[DOCS].asJsonArray[0].asJsonObject[ABSTRACT]
Segun wikipedia "An abstract is a brief summary of a research article", asi que creo que estaria bien

2023-04-25 22:54 UTC, AgusF22 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        private const val NEW_YORK_TIMES_URL = "https://api.nytimes.com/svc/search/v2/"
Eso esta ahi porque es como si fuera un injector (idealmente estaria en su propio archivo con el nombre correspondiente)

2023-04-26 13:00 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(intent.getStringExtra(ARTIST_NAME_EXTRA))
Porque init database hace getArtistInfo?

2023-04-26 13:02 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            var text = getInfoFromDataBase(artistName)
Lo que está dentro del thread es un poco análogo al repositorio. Traten de aplicar el algoritmo de repositorio

2023-04-26 13:03 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        var text = "No Results"
Es rarisimo

2023-04-26 13:04 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        if (text != null)
elvis

2023-04-26 13:05 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        } catch (e: IOException) {
cuando hace un catch además de retornar lo que necesiten hagan un printStackTrace

2023-04-26 20:42 UTC, nicolastradivarius approved these changes

2023-04-26 20:42 UTC, nicolastradivarius commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +import com.google.gson.*
Sería ideal importar solo los paquetes que se van a utilizar del paquete `gson`

2023-04-27 00:50 UTC, CoachVach approved these changes

2023-04-27 00:56 UTC, merged