Entrega 2
elagarrigue/AyDS23-NewYork3 pull request #4
Opened 2023-04-27 01:25 UTC by AgusF22

2023-04-29 19:22 UTC, elagarrigue requested changes
Falta descripción del PR.
- Para poder sacar lógica de vista del algoritmo repository, la función debería retornar un objeto que contenga el string de información, url, y una bandera indicando si estaba en la db o no. Si bien en el enunciado se pide no crear nuevas clases (reestructurando la clase actual), esta nueva clase de dominio es necesaria.

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +class DataBase(context: Context) : SQLiteOpenHelper(context, "dictionary.db", null, 1) {
definir constate para el nombre de la db

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +            "create table artists ($COLUMN_ID integer PRIMARY KEY AUTOINCREMENT, $COLUMN_ARTIST string, $COLUMN_INFO string, $COLUMN_SOURCE integer)"
se puede definir una constante para la query completa

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(intent.getStringExtra(ARTIST_NAME_EXTRA))
hace demasiado, y no necesita ser un parámetro. Mover a un paso dentro de getArtistInfo.

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
- Por nivel de abstracción, el thread debería llamar a una sola función.
- Hace demasiadas cosas, no es el mismo nivel de abstracción.
- Debería estar claro el algoritmo repository.
- Tiene distintos side effects.

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            "No Results"
definir constantes

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getTextFromAbstract(abstract: String?, artistName: String?): String {
artistName se pasa por parámetro a muchas funciones, mejor definir una propiedad

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            return if (docs.size()==0) null else docs
hace mínimo dos cosas, llamar a la api y parsear el resultado json

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }
distintos niveles de abstracción, mover lo del lambda a otra función

2023-04-29 19:22 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            .append("</font></div></html>")
definir constantes

2023-05-02 21:34 UTC, kevschweitzer requested changes

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            val jobj = Gson().fromJson(callResponse.body(), JsonObject::class.java)
Separar la transformación del Json. Ver analogamente como esta hecho en Home (aunque esta en varias clases )

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                PREFIX + "${artistInfo.abstract}" else PREFIX
El prefijo no se tiene que agregar directamente desde en la llamada a la base de datos. Eso es algo de la vista

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        text = textToHtml(textFormatted)
mejor usen return textToHtml(..

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getTextFromAbstract(abstract: String?): String {
Pueden usar una mejora de Kotlin poniendo directamente
```suggestion
    private fun getTextFromAbstract(abstract: String?) = if (abstract != null) {
    } ...
```

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val textWithLineBreaks = textWithSpaces.replace("\n", "<br>")
constantes para los strings

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +        var artistInfo: ArtistInfo? = null
No hace falta definir esta variable en nulo. Eso es estilo Java. En Kotlin pueden poner 
```suggestion
        return try {
        ...
        ArtistInfo(artist, info, url)
        } catch(...) {
        ...
        null
        }
```

2023-05-02 21:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +        val selection = SELECTION_FILTER
estos val no son necesarios. Pueden ponerlos directamente en la query

2023-05-03 12:53 UTC, kevschweitzer approved these changes

2023-05-03 12:54 UTC, merged