Entrega 5
elagarrigue/AyDS23-NewYork3 pull request #7
Opened 2023-06-01 02:41 UTC by nicolastradivarius

**Entrega correspondiente a la abstracción e integración del servicio externo**
Se creó un módulo dedicado para obtener información de un artista en la API de New York Times, `NYTService`, y se encuentra en el siguiente repositorio: https://github.com/AgusF22/AyDS23-NewYork3-NewYorkTimes

Se generalizó el paquete de `moredetails` haciendo que la entidad de ??? sea una clase Card, la cual nos permite interactuar con los distintos módulos/servicios de las demás comisiones de manera transparente. Luego, se integraron al proyecto los servicios de Wikipedia y LastFM mediante el **patrón broker** con proxies por cada módulo, y se adaptó la interfaz de usuario para reflejar la información obtenida del artista ??? los tres servicios mencionados.

2023-06-02 04:11 UTC, kevschweitzer requested changes
Muy bien. Fijense además que si no tienen conectado internet antes de apretar more details les aparece una pantalla negra (Carousel vacio). Fijense de buscar alguna forma de en caso de que la lista esté vacia poder mostrar algun mensaje

2023-06-02 04:11 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/local/nytimes/sqldb/CardLocalStorageImpl.kt
> +    override fun getArtistInfo(artist: String): List<Card>? {
Para representar algo sin resultados mejor una lista vacia en vez de nulo. Fijense que incluso en el repository al final devuelven o cards o una lista vacia si es nulo asi que mas vale representarlo desde aca asi

2023-06-02 04:11 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/view/CarouselAdapter.kt
> +        setImageView(holder.imageView, card.sourceLogoUrl)
Estos metodos deberian estar adentro del Holder. Hacer un metodo en el CarouselViewHolder que se llame setCard por ejemplo y que reciba card y ahi llamar a los setText e Image correspondientes

2023-06-03 20:02 UTC, kevschweitzer commented
Actualicen tambien el diagrama de clases. De los submodulos hagan lo interior del suyo nomas. Los otros pongan solo el paquete para representarlo

2023-06-04 01:22 UTC, nicolastradivarius commented
> Actualicen tambien el diagrama de clases. De los submodulos hagan lo interior del suyo nomas. Los otros pongan solo el paquete para representarlo

Actualizado

2023-06-05 20:45 UTC, nicolastradivarius commented
> Fijense además que si no tienen conectado internet antes de apretar more details les aparece una pantalla negra (Carousel vacio). Fijense de buscar alguna forma de en caso de que la lista esté vacia poder mostrar algun mensaje.

Faltó resolver esto a la hora de pedir la review.

2023-06-06 03:52 UTC, kevschweitzer requested changes
Diagrama de clases:
- Por que sacaron las implementaciones del presenter? Agreguenlas
- La flecha de view al adapter no seria al reves?
- Sacar el enumerado de Source. Eso no es necesario en el diagrama

Ademas terminar con el tema de mostrar un error o mensaje si la lista queda vacia

2023-06-06 03:52 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/view/MoreDetailsView.kt
> +        viewPager = findViewById(R.id.viewPager)
Solo usan el viewPager en el init carousel? En ese caso no es necesario hacerlo variable global. Pongan directamente esto en el initCarousel y listo

2023-06-08 15:23 UTC, kevschweitzer requested changes
Diagrama de clases:
- La flecha entre presenter y helper tiene que ir desde Impl hasta interfaz, no de interfaz a interfaz

Ultimos cambios chiquitos para cerrar

2023-06-08 15:23 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsUIState.kt
> +    var cardList: List<Card> = emptyList()
Esto tiene que ser val. La idea es que la vista al recibir un UIState no pueda cambiar nada, solo consumir. Por eso tiene que ser todo val y solo es var el uiState del override en el presenter. Fijense de actualizarlo como uiState.copy como lo hacian antes

2023-06-09 01:59 UTC, kevschweitzer approved these changes

2023-06-09 01:59 UTC, merged